include RKI sequences in open data instance
GenSpectrum/LAPIS pull request #119
Opened 2023-02-14 13:47 UTC by fengelniederhammer

resolves #114

2023-02-14 13:53 UTC, fengelniederhammer commented on server/src/test/java/ch/ethz/lapis/source/TestDataGenerator.java
> +            System.out.println(rkiEntries.size());
clean up

2023-02-14 14:25 UTC, corneliusroemer commented
Exciting! Let me know how/where I can test :)

2023-02-14 15:37 UTC, chaoran-chen commented
Nice, thanks for implementing it!

It's quite big and difficult to review it in detail (with all the field names, etc.). Should I maybe just run it on the server and see if everything works? With ba520ea4c92798f74ef1ea177afb252da9d93135 that I just pushed, the old data won't be deleted after importing and we can easily reverse.

2023-02-14 15:41 UTC, fengelniederhammer commented
> It's quite big and difficult to review it in detail

Did you review the individual commits? The second commit should be a lot easier to review alone.

2023-02-14 15:58 UTC, chaoran-chen commented
Ah, yes, that's much better. The code looks good! But there will be a problem with using the `nuc-sequence` and `aa-sequence` endpoints afterward because they use the GenBank Accession as key ([source](https://github.com/GenSpectrum/LAPIS/blob/5f61ef5fa17940bf8cbe7f320a2bfc0b563ac862/server/src/main/java/ch/ethz/lapis/api/SampleService.java#L348)).

We should switch the identifier for the fasta files to `strain`. As the endpoint is barely used (I checked the logs), it's fine to just do it.

2023-02-16 12:35 UTC, fengelniederhammer commented
Thanks for catching this! I also added the possibility to specify `fields=database` in the /aggregated and /details to stay consistent on that end.

- [ ] clean up commits before merge

2023-02-16 13:26 UTC, chaoran-chen commented on server/src/main/java/ch/ethz/lapis/source/ng/NextstrainFileToDatabaseService.java
> +                        }
Don't forget to remove this ;)

2023-02-20 08:29 UTC, fengelniederhammer commented on server/src/main/java/ch/ethz/lapis/source/ng/NextstrainFileToDatabaseService.java
> +                        }
Removed it

2023-02-21 09:29 UTC, chaoran-chen commented
I ran the preprocessing pipeline on the server and it works well! One remaining issue is, however, that the RKI data do not contain a `host` but CoV-Spectrum only shows sequences from humans by default. I suggest that we set the `host` of RKI sequences to `Homo sapiens`.

@corneliusroemer, do you know whether it is safe to assume that the RKI sequences are from humans? Would it make sense to change the value for hosts on the Nextstrain side?

2023-02-23 08:34 UTC, JonasKellerer commented
> I ran the preprocessing pipeline on the server and it works well! One remaining issue is, however, that the RKI data do not contain a `host` but CoV-Spectrum only shows sequences from humans by default. I suggest that we set the `host` of RKI sequences to `Homo sapiens`.
> 
> @corneliusroemer, do you know whether it is safe to assume that the RKI sequences are from humans? Would it make sense to change the value for hosts on the Nextstrain side?

The host should now be set to `Homo sapiens` if it is null for the rki data. Could you @chaoran-chen check if the fix works?

2023-02-23 08:38 UTC, chaoran-chen requested changes

2023-02-23 08:38 UTC, chaoran-chen commented on server/src/main/java/ch/ethz/lapis/transform/TransformService.java
> +            set host = "Homo sapiens"
Ah, wait, that's wrong! In SQL, the strings must be in single quotes.

2023-02-23 08:48 UTC, chaoran-chen approved these changes
Thanks! I tried the SQL query and it works. Green lights to merge from my side!

2023-02-23 08:49 UTC, chaoran-chen commented
Oh, wait, stop a moment..

2023-02-23 08:50 UTC, chaoran-chen commented
The commit "[tmp: avoid removing old data after importing for testing purposes](https://github.com/GenSpectrum/LAPIS/pull/119/commits/7b7f89dd8129a54940407baeca2407f8ca9455db)" is back. I actually deleted it two days ago. I'll delete it again and force-push.

2023-02-23 08:52 UTC, chaoran-chen commented
Okay. Done!

2023-02-23 08:57 UTC, merged