313 implement nuc sequence aligned
GenSpectrum/LAPIS pull request #377
Opened 2023-09-13 09:25 UTC by JonasKellerer

Resolves #313 resolves #312 resolves #314

2023-09-13 10:44 UTC, JonasKellerer commented
This PR waits on SILO to implement the "Fasta" action.

2023-09-20 11:31 UTC, fengelniederhammer requested changes
Some details, but overall it looks good :+1:

2023-09-20 11:31 UTC, fengelniederhammer commented on lapis2/src/main/kotlin/org/genspectrum/lapis/OpenApiDocs.kt
> +                )
Is this even used? Anyway using the general LAPIS schema seems wrong here.

2023-09-20 11:31 UTC, fengelniederhammer commented on lapis2/src/main/kotlin/org/genspectrum/lapis/controller/SingleSegmentedSequenceController.kt
> +    "Returns a string of fasta formated aligned nucleotide sequences. Only sequences matching the " +
```suggestion
    "Returns a string of fasta formatted, aligned nucleotide sequences. Only sequences matching the " +
```

2023-09-20 11:31 UTC, fengelniederhammer commented on lapis2/src/main/kotlin/org/genspectrum/lapis/controller/MultiSegmentedSequenceController.kt
> +    "Returns a string of fasta formated aligned nucleotide sequences of the requested segment. " +
```suggestion
    "Returns a string of fasta formatted, aligned nucleotide sequences of the requested segment. " +
```

2023-09-20 11:31 UTC, fengelniederhammer commented on siloLapisTests/test/common.ts
> +});
We could also extract the middleware, since it's the same as for the `lapisClient`, isn't it?

2023-09-25 08:15 UTC, fengelniederhammer approved these changes
Only some typos, etc. Otherwise it looks good :)

2023-09-25 10:05 UTC, merged