#69: Usage and performance statistics
GenSpectrum/LAPIS pull request #85
Opened 2023-01-23 10:45 UTC by JonasKellerer

Resolves #69

2023-01-23 11:37 UTC, fengelniederhammer commented on server/build.gradle
> +    testImplementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
- [ ] remove

2023-01-23 12:15 UTC, chaoran-chen requested changes
Thanks! This works already quite well. Just a few things:

The insertions and mutations (both AA and nuc) are logged in the decoded form, e.g. as `[{"gene":"S","position":501,"query":"YYY"}]` or `[{"gene":"S","position":501,"mutation":"Y","applyMaybe":false}]`. That's very unhandy and it would be better if they could be logged using the short and standardized notation. I.e., as `ins_S:501:YYY` and `S:501Y`.

It would also be great if the fields with a `null` could be omitted.

2023-01-23 12:15 UTC, chaoran-chen commented on server/src/main/java/ch/ethz/lapis/api/log/RequestContext.java
> +    private SampleFilter variantFilter;
this should better just be called `filter` as it includes more than the variant.

2023-01-23 14:23 UTC, JonasKellerer commented
The new log will look similar to this.

`{"timestamp":"2023-01-23T15:04:46.364506146","responseTimeInSeconds":0.007652409,"endpoint":"/v1/sample/aggregated","returnedDataFromCache":false,"filter":{"country":"Germany","nucMutations":[],"nucInsertions":[],"aaMutations":["S:501Y"],"aaInsertions":["ins_S:2345:EN"],"fields":["DATE","PANGOLINEAGE"]}}`

Is this, what you imagined?

2023-01-23 14:45 UTC, chaoran-chen requested changes
The log looks great but something else went wrong.

If I open http://localhost:2345/v1/sample/aggregated?country=Switzerland&aaMutations=S:E484K,S:N501Y&fields=country, I get

```
{"errors":[],"info":{"apiVersion":1,"dataVersion":1665960786},"data":{"fields":["COUNTRY"],"samples":[{"country":"Switzerland","count":611}]}}
```

The wrapper around the samples is new. https://lapis.cov-spectrum.org/open/v1/sample/aggregated?country=Switzerland&aaMutations=S:E484K,S:N501Y&fields=country returns:

```
{"errors":[],"info":{"apiVersion":1,"dataVersion":1674178709,"deprecationDate":null,"deprecationInfo":null,"acknowledgement":null},"data":[{"country":"Switzerland","count":483}]}
```

---

Apart from that, a small request: it would be better to return the response time in milliseconds and as an integer.

2023-01-24 12:51 UTC, chaoran-chen requested changes
One last request: It would be better to log the timestamp with the time zone or as the Unix timestamp so that it is actually clear which time it was without knowing the server config.

Otherwise, it looks good to me!

2023-01-24 13:13 UTC, chaoran-chen approved these changes
Great! Thank you!

2023-01-24 13:16 UTC, merged